### PR TITLE
5.0 love data saving

### PR DESCRIPTION
**Pull request by Driesboy**

### CODE REVIEW

**Comment by Driesboy** [comment]
you just need to make that a player who already has a girlfriend can receive love Request

**Comment by TheDeibo** [comment]
THat was actually on the planning list. I have a lot instore for 4.0, so this update still will be 4.0 xD

**Comment by Driesboy** [comment]
ok i will change it back to 4.0

**Comment by Driesboy** [comment]
please see the changes i have change that you can get max 1 heart
and that you can max love 1 player 

but i have 1 problem
you just need to make that a player who already has a girlfriend can receive love Request

**Comment by TheDeibo** [comment]
That is already planned :3 

Basically @ratchetgame98 and I are doing it in our spare time. We are going to be joining ideas. ( like they are porting off each other ) 
Check out his Java plugin ( For Bukkit ) https://github.com/ratchetgame98/ServerLove

**Comment by Driesboy** [comment]
Can you merge it?

**Comment by Driesboy** [comment]
Soon i will add accept and deny ok

**Comment by TheDeibo** [comment]
Im merging it but through making it my own commit. ( The commit update will show your name though ) Reason.... few changes

**Comment by Driesboy** [comment]
ok!!!

**Pull request closed without merging**
