### PR TITLE
The Baby Update!

### PR DESCRIPTION
**Pull request by TheDeibo**
Many thanks to @mcpepig and @Driesboy.

### CODE REVIEW

**Comment by TheDeibo** [comment]
This is still not a actual released version just yet. It needs checking, and fixing, but its just here. :)

**Comment by Driesboy** [comment]
its not fully fixed for now

**Comment by Driesboy** [comment]
how i can fix?

**Comment by MCPEPIG** [comment]
Using $pk->metedata = [ALL YOUR TAGS]

**Comment by Driesboy** [comment]
make a pr

**Comment by Driesboy** [comment]
plz report all the bugs to my repository

**Pull request merged**
